[project]
name = "dev_workflow_pull_request__open"
version = "0.0.1"
dependencies = [
    "dev_workflow_utils @ file:///${REPO_ROOT}/shared/utils",
    "boto3==1.28.42"
]

[tool.setuptools.packages]
find = {}
